/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VulnerabilitiesRouteImport } from './routes/vulnerabilities'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReconRouteImport } from './routes/recon'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as NewScanRouteImport } from './routes/new-scan'
import { Route as IndexRouteImport } from './routes/index'

const VulnerabilitiesRoute = VulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconRoute = ReconRouteImport.update({
  id: '/recon',
  path: '/recon',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const NewScanRoute = NewScanRouteImport.update({
  id: '/new-scan',
  path: '/new-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-scan': typeof NewScanRoute
  '/plugins': typeof PluginsRoute
  '/recon': typeof ReconRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-scan': typeof NewScanRoute
  '/plugins': typeof PluginsRoute
  '/recon': typeof ReconRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-scan': typeof NewScanRoute
  '/plugins': typeof PluginsRoute
  '/recon': typeof ReconRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new-scan'
    | '/plugins'
    | '/recon'
    | '/reports'
    | '/settings'
    | '/vulnerabilities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new-scan'
    | '/plugins'
    | '/recon'
    | '/reports'
    | '/settings'
    | '/vulnerabilities'
  id:
    | '__root__'
    | '/'
    | '/new-scan'
    | '/plugins'
    | '/recon'
    | '/reports'
    | '/settings'
    | '/vulnerabilities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewScanRoute: typeof NewScanRoute
  PluginsRoute: typeof PluginsRoute
  ReconRoute: typeof ReconRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  VulnerabilitiesRoute: typeof VulnerabilitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vulnerabilities': {
      id: '/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof VulnerabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recon': {
      id: '/recon'
      path: '/recon'
      fullPath: '/recon'
      preLoaderRoute: typeof ReconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-scan': {
      id: '/new-scan'
      path: '/new-scan'
      fullPath: '/new-scan'
      preLoaderRoute: typeof NewScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewScanRoute: NewScanRoute,
  PluginsRoute: PluginsRoute,
  ReconRoute: ReconRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  VulnerabilitiesRoute: VulnerabilitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
